web:
  build: .
  command: npm run start
  ports:
    - "8080:8080"
  volumes:
    - ./.eslintrc:/var/www/.eslintrc
    - ./webpack.config.js:/var/www/webpack.config.js
    - ./dist:/var/www/dist
    - ./src:/var/www/src
    - ./package.json:/var/www/package.json
